### ISSUE TITLE
Sign up =>Sign up page + Sign up thanks

### ISSUE THREAD

**Issue by Nadim-absi** [Recoded-Spark-Turkey-2022/Unboxed#13]
New feature: the main Sign up page
**Requirements for this issue:**

- [x]  Full Completion design wise
- [x]  Mobile Compatibly
- [x]  Test.js

**Logical Requirements:**

- [ ] Checking validity of information inputted
- [x] Can sign up using (email, google and Facebook)
- [x] Once signed up, Firebase will be updated

![image](https://user-images.githubusercontent.com/113457314/209427542-8b1f82cd-b75a-4e92-80ad-4c4143904efe.png)

**Comment by akbulatesra** [comment]
<img width="1440" alt="Screen Shot 2023-01-01 at 22 14 56" src="https://user-images.githubusercontent.com/64817771/210182259-63e9ef61-456c-49d2-977c-751b97b1e4de.png">

**Comment by Nadim-absi** [comment]
Great work on the design and functionality!!
