### ISSUE TITLE
About => Careers (Half Page)

### ISSUE THREAD

**Issue by akbulatesra** [Recoded-Spark-Turkey-2022/Unboxed#20]
- [ ]  Full Completion design wise
- [ ]  Mobile Compatibly
- [ ] Test.js

![Careers](https://user-images.githubusercontent.com/64817771/210167914-e58a7312-137a-42f3-a631-d64284a828fe.jpg)

**Comment by Nadim-absi** [comment]
Current Iteration:
![image](https://user-images.githubusercontent.com/113457314/210578130-f6a95a64-8d1d-48c5-b423-818bb22e64c3.png)

Sizes done according to Figma file, but they seem too large.  I would suggest decreasing sizes a bit
