### ISSUE TITLE
Counselor=> Therapist Create + Therapist Thanks

### ISSUE THREAD

**Issue by pelinkarakoca** [Recoded-Spark-Turkey-2022/Unboxed#37]
- [x]  Full Completion design wise
- [x]  Mobile Compatibly
- [ ] Test.js
- [x] Connect with firebase

<img width="802" alt="Screenshot 2023-01-13 at 22 15 00" src="https://user-images.githubusercontent.com/90033522/212400396-b5b716e1-3e83-46d8-8fc0-02ee34d5b682.png">
<img width="803" alt="Screenshot 2023-01-13 at 22 15 51" src="https://user-images.githubusercontent.com/90033522/212400543-57396113-2b64-441e-8229-97bdd885e3fa.png">

**Comment by Nadim-absi** [comment]
I'll start working on this and see where it goes.

**Comment by Nadim-absi** [comment]
Issue completd, view #47 

**Note**:  tests will be added later for time sake.
