### ISSUE TITLE
Counselor => Counselor Page

### ISSUE THREAD

**Issue by pelinkarakoca** [Recoded-Spark-Turkey-2022/Unboxed#39]
- [x] Full completion design wise
- [x] Mobile compatibility 
- [ ] Test.js

**Comment by pelinkarakoca** [comment]
<img width="678" alt="Screenshot 2023-01-13 at 22 21 12" src="https://user-images.githubusercontent.com/90033522/212401627-6e004cac-bd10-4b59-b420-7c1efc6211c7.png">

**Comment by Nadim-absi** [comment]
closed with #54
