### ISSUE TITLE
Testing=> Overall navigation/Functionality/Design

### ISSUE THREAD

**Issue by pelinkarakoca** [Recoded-Spark-Turkey-2022/Unboxed#40]
- [ ] Overall navigation
- [ ] Design testing (Including responsiveness)

**Comment by Nadim-absi** [comment]
Detailed List of bugs to be fixed:
Add more if required. 

**Nabar**
- [x] Dropdown of about and login need to be adjusted for margin and design
- [x] Add transition to dropdown if possible
- [x] Navbar height?

**Counselor create**
- [ ] Does not indicate if email is already in use 
- [ ] Alert to require user to fill all info

**Homepage**
- [ ] Counselor component is not centred
- [ ] Button navigation needs to be functionalized

**Footer**
- [x] Footer height is too large
- [x] Mobile compatibility needs adjustment



**Signup**
- [x] Pass empty Tickets when creating doc
- [x] Pass empty cards when creating doc
