### ISSUE TITLE
Testing => Design

### ISSUE THREAD

**Issue by pelinkarakoca** [Recoded-Spark-Turkey-2022/Unboxed#56]
### **HOMEPAGE**
- [ ] All fonts and button size be compatible with each other
- [ ] Height and width be compatible with each other
- [ ] Button hover colors needs to be same
- **Hero section**
 - [ ] responsiveness is not working: the image is too little and the text is too big 
 - [ ] padding needs to be fixed
<img width="514" alt="Screenshot 2023-01-27 at 14 24 35" src="https://user-images.githubusercontent.com/90033522/215075016-a62ebde3-b835-4f7f-86a7-8ee02b88bec0.png">

- **Yellow section**
- [ ] book an appointment button is too big.
- [ ] subtitle and text are not shrink when the page is shrunk.
- [ ] the hero section and yellow section have the same 'book an appointment" button, but they look different.
<img width="583" alt="Screenshot 2023-01-27 at 14 31 24" src="https://user-images.githubusercontent.com/90033522/215076317-de400e41-7fd7-4f80-9682-8f3754bab744.png">

-**Blog Slider**
- [x] height needs to be changed.
- [ ] for small pages, the heading is bold. change it.

-**Counselor Card**
- [ ] for small screens, fonts need to be adjusted

**Comment by pelinkarakoca** [comment]
### **NAVBAR**

- [ ] W & h be compatible
- [ ] Fonts be compatible w others
- [x] Margins from right
- [x] Dropdowns
- [x] Responsiveness

###**FOOTER**
- [ ] W & h be compatible
- [ ] Fonts be compatible with others
- [ ] Footer social media icons a little bit away from the footer links (because right now, it looks like they relate with each other)
<img width="465" alt="Screenshot 2023-01-27 at 18 06 07" src="https://user-images.githubusercontent.com/90033522/215118889-c0f99a3e-7666-4092-8468-9df4bf020e4c.png">

**Comment by pelinkarakoca** [comment]
### **ABOUT**
-**Overview**
- [ ] small screens => gap btw components need to be smaller
- [ ] fonts will be compatible with others

**Comment by pelinkarakoca** [comment]
### **CONTACT US**
- [x] make responsive
- [ ] top of the content is not shown due to navbar (on mobile)
- [x] when scrolling, the content appear on navbar
- [x] fonts will be compatible with others

**Comment by Nadim-absi** [comment]
### About/Team:

- [ ] Images overlap with footer
- [x] Change mad eye moody pic
- [x] Addition of github/linkdiln links

**Comment by Nadim-absi** [comment]
### Pages that need adjustments for larger screens:

- [ ] Contact
- [ ] About/Team
- [ ] But Ticket
- [ ] Add Card
- [ ] Sign up
- [ ] Payment Methods
- [ ] Counsellor Requirements
- [ ] Counsellor Signup

**Comment by ysfdumlu** [comment]
Hero,Communicate and Yellow Secs. are my first try so 😪eğitim zayiatı o 3 ü :)
1-For Hero Section there is a problem between 400 and 640 pixel,
2-For image i cant adjust it bigger with small effort, this is also good i think. Smaller font size easier to do.
3-Font için 11. satırdaki div e sadece font-poppins eklencek onu atlamışım. (ekleyip main e push layacaktımda vazgeçtim alışkanlık yapmasın :D)
-Button size is also different in given Figma %20 bigger one of them
-button hover color i did all same
4-i tried shrink thing in the yellow sec. they are shrink but if you say text-size yes i think they should be 1 or 2 tık smaller when -page under 640px
-Communicate section a ise birşeyler olmuş i did not even understand what happened there i am very very much sure it is not like that when i pushed also checked at that time.

-If you guys want i can simply fix 3, 4(if i understand right), and 2 by using smaller font size but 1 and larger image takes more time which i dont have much
