### ISSUE TITLE
Translation Implementing

### ISSUE THREAD

**Issue by akbulatesra** [Recoded-Spark-Turkey-2022/Unboxed#59]
- [x] Implementing translation library to project
- [x] Adding language part to navbar

Creating translation files for:

- [x] Turkish
- [x] English
- [x] Arabic

**Comment by Nadim-absi** [comment]
![image](https://user-images.githubusercontent.com/113457314/215314901-a50497d4-c21d-4478-b619-a0199ee16a67.png)
Strored in a local state:
![image](https://user-images.githubusercontent.com/113457314/215314928-ab4a0172-c7c2-4930-b1d4-4615574f508d.png)
