### ISSUE TITLE
Homepage=>BlogsSlider

### ISSUE THREAD

**Issue by Nadim-absi** [Recoded-Spark-Turkey-2022/Unboxed#6]
New feature: the main Blogs Slider of the homepage
Requirements for this issue:

- [x]  Full Completion design wise
- [x]  Mobile Compatibly
- [x]  Test.js
- [x] Blog slider contain 3 different blogs min.
- [x] Blog slider links to the blog clicked 

No need to create actual blog page now. Just link to ex: blog/menatalhealth, blog/healfromtrauma

**Comment by pelinkarakoca** [comment]
<img width="1435" alt="Screenshot 2023-01-03 at 17 46 15" src="https://user-images.githubusercontent.com/90033522/210380193-861b0ca0-ad7a-4523-83ed-e0031321e46f.png">

**Comment by Nadim-absi** [comment]
!Perfection!
