### ISSUE TITLE
Homepage=> ticket section

### ISSUE THREAD

**Issue by Nadim-absi** [Recoded-Spark-Turkey-2022/Unboxed#7]
New feature: the main Communicate section of the homepage
Requirements for this issue:

- [x]  Full Completion design wise
- [x]  Mobile Compatibly
- [x]  Test.js

![image](https://user-images.githubusercontent.com/113457314/209426697-77e2a1d5-142b-44cb-9362-79a4fb67a119.png)

For now the buttons will not link to anything.

**Comment by pelinkarakoca** [comment]
<img width="1180" alt="Screenshot 2023-01-01 at 22 22 34" src="https://user-images.githubusercontent.com/90033522/210182379-3c66e656-c063-4b9a-9482-e9e83c95f417.png">

**Comment by pelinkarakoca** [comment]
<img width="376" alt="Screenshot 2023-01-01 at 22 24 41" src="https://user-images.githubusercontent.com/90033522/210182437-b45bd1be-1f4e-4100-9a66-9f0619344837.png">
